/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unmsm.ochotorres.interfazgrafica;

import com.unmsm.ochotorres.Tablero;

/**
 *
 * @author pc
 */
public class TableroPresenter extends javax.swing.JPanel {

    CeldaPresenter[][] matriz;
    Tablero tableroModelo;

    public TableroPresenter() {
        initComponents();
    }
    
    public void construirEnBaseA(Tablero tablero){
        tableroModelo=tablero;
        this.removeAll();
        matriz = new CeldaPresenter[Tablero.DIMENSION][Tablero.DIMENSION];
        for (int fila = 0; fila < Tablero.DIMENSION; fila++) {
            for (int columna = 0; columna < Tablero.DIMENSION; columna++) {
                
                Posicion posicion =new Posicion(50 * columna, 50 * fila, 50, 50);
                CeldaPresenter celdaPresenter = new CeldaPresenter(posicion,tablero.getCelda(fila + 1, columna + 1));
                celdaPresenter.establecerPanel(this);        
                matriz[fila][columna] = celdaPresenter;
                this.add(matriz[fila][columna]);
            }
        }
        this.updateUI();

    }

    public Tablero getTableroModelo() {
        return tableroModelo;
    }

   
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
