/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unmsm.ochotorres.interfazgrafica;

import com.unmsm.ochotorres.Tablero;

/**
 *
 * @author pc
 */
public class TableroPresenter extends javax.swing.JPanel {

    /**
     * Creates new form PanelTablero
     */
    public TableroPresenter() {
        initComponents();
    }
    
    public void construirTablero(Tablero tablero){
        this.removeAll();
        int filas = Tablero.DIMENSION_X;
        int columnas = Tablero.DIMENSION_Y;
        CeldaPresenter[][] tableroPresenter = new CeldaPresenter[filas][columnas];
        for (int fila = 0; fila < filas; fila++) {
            //Estando en la fila se recorrer las columnas
            for (int columna = 0; columna < columnas; columna++) {
                CeldaPresenter celdaPresenter = new CeldaPresenter(50 * columna, 50 * fila, 50, 50);
                Tablero.Celda celdaContenido = tablero.getCelda(fila + 1, columna + 1);
                celdaPresenter.establecerContenido(celdaContenido);
                celdaPresenter.establecerContenedor(tablero);
                celdaPresenter.establecerPanel(this);
                celdaPresenter.establecerIcono(celdaContenido.obtenerEstado());
                tableroPresenter[fila][columna] = celdaPresenter;

                this.add(tableroPresenter[fila][columna]);
            }
        }
        this.updateUI();

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
